// Code generated by idlgen. DO NOT EDIT.
// Source: Windows SDK IDL files (d3d11.idl, dxgi.idl, etc.)
package main

// COM vtable 方法索引常量（含继承链）
const (
	// ID3D11Asynchronous
	VT_ID3D11Asynchronous_GetDataSize = 7

	// ID3D11AuthenticatedChannel
	VT_ID3D11AuthenticatedChannel_GetCertificateSize = 7
	VT_ID3D11AuthenticatedChannel_GetCertificate     = 8
	VT_ID3D11AuthenticatedChannel_GetChannelHandle   = 9

	// ID3D11BlendState
	VT_ID3D11BlendState_GetDesc = 7

	// ID3D11BlendState1
	VT_ID3D11BlendState1_GetDesc1 = 8

	// ID3D11Buffer
	VT_ID3D11Buffer_GetDesc = 10

	// ID3D11ClassInstance
	VT_ID3D11ClassInstance_GetClassLinkage = 7
	VT_ID3D11ClassInstance_GetDesc         = 8
	VT_ID3D11ClassInstance_GetInstanceName = 9
	VT_ID3D11ClassInstance_GetTypeName     = 10

	// ID3D11ClassLinkage
	VT_ID3D11ClassLinkage_GetClassInstance    = 7
	VT_ID3D11ClassLinkage_CreateClassInstance = 8

	// ID3D11CommandList
	VT_ID3D11CommandList_GetContextFlags = 7

	// ID3D11Counter
	VT_ID3D11Counter_GetDesc = 8

	// ID3D11CryptoSession
	VT_ID3D11CryptoSession_GetCryptoType          = 7
	VT_ID3D11CryptoSession_GetDecoderProfile      = 8
	VT_ID3D11CryptoSession_GetCertificateSize     = 9
	VT_ID3D11CryptoSession_GetCertificate         = 10
	VT_ID3D11CryptoSession_GetCryptoSessionHandle = 11

	// ID3D11DepthStencilState
	VT_ID3D11DepthStencilState_GetDesc = 7

	// ID3D11DepthStencilView
	VT_ID3D11DepthStencilView_GetDesc = 8

	// ID3D11Device
	VT_ID3D11Device_CreateBuffer                         = 3
	VT_ID3D11Device_CreateTexture1D                      = 4
	VT_ID3D11Device_CreateTexture2D                      = 5
	VT_ID3D11Device_CreateTexture3D                      = 6
	VT_ID3D11Device_CreateShaderResourceView             = 7
	VT_ID3D11Device_CreateUnorderedAccessView            = 8
	VT_ID3D11Device_CreateRenderTargetView               = 9
	VT_ID3D11Device_CreateDepthStencilView               = 10
	VT_ID3D11Device_CreateInputLayout                    = 11
	VT_ID3D11Device_CreateVertexShader                   = 12
	VT_ID3D11Device_CreateGeometryShader                 = 13
	VT_ID3D11Device_CreateGeometryShaderWithStreamOutput = 14
	VT_ID3D11Device_CreatePixelShader                    = 15
	VT_ID3D11Device_CreateHullShader                     = 16
	VT_ID3D11Device_CreateDomainShader                   = 17
	VT_ID3D11Device_CreateComputeShader                  = 18
	VT_ID3D11Device_CreateClassLinkage                   = 19
	VT_ID3D11Device_CreateBlendState                     = 20
	VT_ID3D11Device_CreateDepthStencilState              = 21
	VT_ID3D11Device_CreateRasterizerState                = 22
	VT_ID3D11Device_CreateSamplerState                   = 23
	VT_ID3D11Device_CreateQuery                          = 24
	VT_ID3D11Device_CreatePredicate                      = 25
	VT_ID3D11Device_CreateCounter                        = 26
	VT_ID3D11Device_CreateDeferredContext                = 27
	VT_ID3D11Device_OpenSharedResource                   = 28
	VT_ID3D11Device_CheckFormatSupport                   = 29
	VT_ID3D11Device_CheckMultisampleQualityLevels        = 30
	VT_ID3D11Device_CheckCounterInfo                     = 31
	VT_ID3D11Device_CheckCounter                         = 32
	VT_ID3D11Device_CheckFeatureSupport                  = 33
	VT_ID3D11Device_GetPrivateData                       = 34
	VT_ID3D11Device_SetPrivateData                       = 35
	VT_ID3D11Device_SetPrivateDataInterface              = 36
	VT_ID3D11Device_GetFeatureLevel                      = 37
	VT_ID3D11Device_GetCreationFlags                     = 38
	VT_ID3D11Device_GetDeviceRemovedReason               = 39
	VT_ID3D11Device_GetImmediateContext                  = 40
	VT_ID3D11Device_SetExceptionMode                     = 41
	VT_ID3D11Device_GetExceptionMode                     = 42

	// ID3D11Device1
	VT_ID3D11Device1_GetImmediateContext1     = 43
	VT_ID3D11Device1_CreateDeferredContext1   = 44
	VT_ID3D11Device1_CreateBlendState1        = 45
	VT_ID3D11Device1_CreateRasterizerState1   = 46
	VT_ID3D11Device1_CreateDeviceContextState = 47
	VT_ID3D11Device1_OpenSharedResource1      = 48
	VT_ID3D11Device1_OpenSharedResourceByName = 49

	// ID3D11Device2
	VT_ID3D11Device2_GetImmediateContext2           = 50
	VT_ID3D11Device2_CreateDeferredContext2         = 51
	VT_ID3D11Device2_GetResourceTiling              = 52
	VT_ID3D11Device2_CheckMultisampleQualityLevels1 = 53

	// ID3D11Device3
	VT_ID3D11Device3_CreateTexture2D1           = 54
	VT_ID3D11Device3_CreateTexture3D1           = 55
	VT_ID3D11Device3_CreateRasterizerState2     = 56
	VT_ID3D11Device3_CreateShaderResourceView1  = 57
	VT_ID3D11Device3_CreateUnorderedAccessView1 = 58
	VT_ID3D11Device3_CreateRenderTargetView1    = 59
	VT_ID3D11Device3_CreateQuery1               = 60
	VT_ID3D11Device3_GetImmediateContext3       = 61
	VT_ID3D11Device3_CreateDeferredContext3     = 62
	VT_ID3D11Device3_WriteToSubresource         = 63
	VT_ID3D11Device3_ReadFromSubresource        = 64

	// ID3D11DeviceChild
	VT_ID3D11DeviceChild_GetDevice               = 3
	VT_ID3D11DeviceChild_GetPrivateData          = 4
	VT_ID3D11DeviceChild_SetPrivateData          = 5
	VT_ID3D11DeviceChild_SetPrivateDataInterface = 6

	// ID3D11DeviceContext
	VT_ID3D11DeviceContext_VSSetConstantBuffers                      = 7
	VT_ID3D11DeviceContext_PSSetShaderResources                      = 8
	VT_ID3D11DeviceContext_PSSetShader                               = 9
	VT_ID3D11DeviceContext_PSSetSamplers                             = 10
	VT_ID3D11DeviceContext_VSSetShader                               = 11
	VT_ID3D11DeviceContext_DrawIndexed                               = 12
	VT_ID3D11DeviceContext_Draw                                      = 13
	VT_ID3D11DeviceContext_Map                                       = 14
	VT_ID3D11DeviceContext_Unmap                                     = 15
	VT_ID3D11DeviceContext_PSSetConstantBuffers                      = 16
	VT_ID3D11DeviceContext_IASetInputLayout                          = 17
	VT_ID3D11DeviceContext_IASetVertexBuffers                        = 18
	VT_ID3D11DeviceContext_IASetIndexBuffer                          = 19
	VT_ID3D11DeviceContext_DrawIndexedInstanced                      = 20
	VT_ID3D11DeviceContext_DrawInstanced                             = 21
	VT_ID3D11DeviceContext_GSSetConstantBuffers                      = 22
	VT_ID3D11DeviceContext_GSSetShader                               = 23
	VT_ID3D11DeviceContext_IASetPrimitiveTopology                    = 24
	VT_ID3D11DeviceContext_VSSetShaderResources                      = 25
	VT_ID3D11DeviceContext_VSSetSamplers                             = 26
	VT_ID3D11DeviceContext_Begin                                     = 27
	VT_ID3D11DeviceContext_End                                       = 28
	VT_ID3D11DeviceContext_GetData                                   = 29
	VT_ID3D11DeviceContext_SetPredication                            = 30
	VT_ID3D11DeviceContext_GSSetShaderResources                      = 31
	VT_ID3D11DeviceContext_GSSetSamplers                             = 32
	VT_ID3D11DeviceContext_OMSetRenderTargets                        = 33
	VT_ID3D11DeviceContext_OMSetRenderTargetsAndUnorderedAccessViews = 34
	VT_ID3D11DeviceContext_OMSetBlendState                           = 35
	VT_ID3D11DeviceContext_OMSetDepthStencilState                    = 36
	VT_ID3D11DeviceContext_SOSetTargets                              = 37
	VT_ID3D11DeviceContext_DrawAuto                                  = 38
	VT_ID3D11DeviceContext_DrawIndexedInstancedIndirect              = 39
	VT_ID3D11DeviceContext_DrawInstancedIndirect                     = 40
	VT_ID3D11DeviceContext_Dispatch                                  = 41
	VT_ID3D11DeviceContext_DispatchIndirect                          = 42
	VT_ID3D11DeviceContext_RSSetState                                = 43
	VT_ID3D11DeviceContext_RSSetViewports                            = 44
	VT_ID3D11DeviceContext_RSSetScissorRects                         = 45
	VT_ID3D11DeviceContext_CopySubresourceRegion                     = 46
	VT_ID3D11DeviceContext_CopyResource                              = 47
	VT_ID3D11DeviceContext_UpdateSubresource                         = 48
	VT_ID3D11DeviceContext_CopyStructureCount                        = 49
	VT_ID3D11DeviceContext_ClearRenderTargetView                     = 50
	VT_ID3D11DeviceContext_ClearUnorderedAccessViewUint              = 51
	VT_ID3D11DeviceContext_ClearUnorderedAccessViewFloat             = 52
	VT_ID3D11DeviceContext_ClearDepthStencilView                     = 53
	VT_ID3D11DeviceContext_GenerateMips                              = 54
	VT_ID3D11DeviceContext_SetResourceMinLOD                         = 55
	VT_ID3D11DeviceContext_GetResourceMinLOD                         = 56
	VT_ID3D11DeviceContext_ResolveSubresource                        = 57
	VT_ID3D11DeviceContext_ExecuteCommandList                        = 58
	VT_ID3D11DeviceContext_HSSetShaderResources                      = 59
	VT_ID3D11DeviceContext_HSSetShader                               = 60
	VT_ID3D11DeviceContext_HSSetSamplers                             = 61
	VT_ID3D11DeviceContext_HSSetConstantBuffers                      = 62
	VT_ID3D11DeviceContext_DSSetShaderResources                      = 63
	VT_ID3D11DeviceContext_DSSetShader                               = 64
	VT_ID3D11DeviceContext_DSSetSamplers                             = 65
	VT_ID3D11DeviceContext_DSSetConstantBuffers                      = 66
	VT_ID3D11DeviceContext_CSSetShaderResources                      = 67
	VT_ID3D11DeviceContext_CSSetUnorderedAccessViews                 = 68
	VT_ID3D11DeviceContext_CSSetShader                               = 69
	VT_ID3D11DeviceContext_CSSetSamplers                             = 70
	VT_ID3D11DeviceContext_CSSetConstantBuffers                      = 71
	VT_ID3D11DeviceContext_VSGetConstantBuffers                      = 72
	VT_ID3D11DeviceContext_PSGetShaderResources                      = 73
	VT_ID3D11DeviceContext_PSGetShader                               = 74
	VT_ID3D11DeviceContext_PSGetSamplers                             = 75
	VT_ID3D11DeviceContext_VSGetShader                               = 76
	VT_ID3D11DeviceContext_PSGetConstantBuffers                      = 77
	VT_ID3D11DeviceContext_IAGetInputLayout                          = 78
	VT_ID3D11DeviceContext_IAGetVertexBuffers                        = 79
	VT_ID3D11DeviceContext_IAGetIndexBuffer                          = 80
	VT_ID3D11DeviceContext_GSGetConstantBuffers                      = 81
	VT_ID3D11DeviceContext_GSGetShader                               = 82
	VT_ID3D11DeviceContext_IAGetPrimitiveTopology                    = 83
	VT_ID3D11DeviceContext_VSGetShaderResources                      = 84
	VT_ID3D11DeviceContext_VSGetSamplers                             = 85
	VT_ID3D11DeviceContext_GetPredication                            = 86
	VT_ID3D11DeviceContext_GSGetShaderResources                      = 87
	VT_ID3D11DeviceContext_GSGetSamplers                             = 88
	VT_ID3D11DeviceContext_OMGetRenderTargets                        = 89
	VT_ID3D11DeviceContext_OMGetRenderTargetsAndUnorderedAccessViews = 90
	VT_ID3D11DeviceContext_OMGetBlendState                           = 91
	VT_ID3D11DeviceContext_OMGetDepthStencilState                    = 92
	VT_ID3D11DeviceContext_SOGetTargets                              = 93
	VT_ID3D11DeviceContext_RSGetState                                = 94
	VT_ID3D11DeviceContext_RSGetViewports                            = 95
	VT_ID3D11DeviceContext_RSGetScissorRects                         = 96
	VT_ID3D11DeviceContext_HSGetShaderResources                      = 97
	VT_ID3D11DeviceContext_HSGetShader                               = 98
	VT_ID3D11DeviceContext_HSGetSamplers                             = 99
	VT_ID3D11DeviceContext_HSGetConstantBuffers                      = 100
	VT_ID3D11DeviceContext_DSGetShaderResources                      = 101
	VT_ID3D11DeviceContext_DSGetShader                               = 102
	VT_ID3D11DeviceContext_DSGetSamplers                             = 103
	VT_ID3D11DeviceContext_DSGetConstantBuffers                      = 104
	VT_ID3D11DeviceContext_CSGetShaderResources                      = 105
	VT_ID3D11DeviceContext_CSGetUnorderedAccessViews                 = 106
	VT_ID3D11DeviceContext_CSGetShader                               = 107
	VT_ID3D11DeviceContext_CSGetSamplers                             = 108
	VT_ID3D11DeviceContext_CSGetConstantBuffers                      = 109
	VT_ID3D11DeviceContext_ClearState                                = 110
	VT_ID3D11DeviceContext_Flush                                     = 111
	VT_ID3D11DeviceContext_GetType                                   = 112
	VT_ID3D11DeviceContext_GetContextFlags                           = 113
	VT_ID3D11DeviceContext_FinishCommandList                         = 114

	// ID3D11DeviceContext1
	VT_ID3D11DeviceContext1_CopySubresourceRegion1 = 115
	VT_ID3D11DeviceContext1_UpdateSubresource1     = 116
	VT_ID3D11DeviceContext1_DiscardResource        = 117
	VT_ID3D11DeviceContext1_DiscardView            = 118
	VT_ID3D11DeviceContext1_VSSetConstantBuffers1  = 119
	VT_ID3D11DeviceContext1_HSSetConstantBuffers1  = 120
	VT_ID3D11DeviceContext1_DSSetConstantBuffers1  = 121
	VT_ID3D11DeviceContext1_GSSetConstantBuffers1  = 122
	VT_ID3D11DeviceContext1_PSSetConstantBuffers1  = 123
	VT_ID3D11DeviceContext1_CSSetConstantBuffers1  = 124
	VT_ID3D11DeviceContext1_VSGetConstantBuffers1  = 125
	VT_ID3D11DeviceContext1_HSGetConstantBuffers1  = 126
	VT_ID3D11DeviceContext1_DSGetConstantBuffers1  = 127
	VT_ID3D11DeviceContext1_GSGetConstantBuffers1  = 128
	VT_ID3D11DeviceContext1_PSGetConstantBuffers1  = 129
	VT_ID3D11DeviceContext1_CSGetConstantBuffers1  = 130
	VT_ID3D11DeviceContext1_SwapDeviceContextState = 131
	VT_ID3D11DeviceContext1_ClearView              = 132
	VT_ID3D11DeviceContext1_DiscardView1           = 133

	// ID3D11DeviceContext2
	VT_ID3D11DeviceContext2_UpdateTileMappings   = 134
	VT_ID3D11DeviceContext2_CopyTileMappings     = 135
	VT_ID3D11DeviceContext2_CopyTiles            = 136
	VT_ID3D11DeviceContext2_UpdateTiles          = 137
	VT_ID3D11DeviceContext2_ResizeTilePool       = 138
	VT_ID3D11DeviceContext2_TiledResourceBarrier = 139
	VT_ID3D11DeviceContext2_IsAnnotationEnabled  = 140
	VT_ID3D11DeviceContext2_SetMarkerInt         = 141
	VT_ID3D11DeviceContext2_BeginEventInt        = 142
	VT_ID3D11DeviceContext2_EndEvent             = 143

	// ID3D11DeviceContext3
	VT_ID3D11DeviceContext3_Flush1                     = 144
	VT_ID3D11DeviceContext3_SetHardwareProtectionState = 145
	VT_ID3D11DeviceContext3_GetHardwareProtectionState = 146

	// ID3D11DeviceContext4
	VT_ID3D11DeviceContext4_Signal = 147
	VT_ID3D11DeviceContext4_Wait   = 148

	// ID3D11Fence
	VT_ID3D11Fence_CreateSharedHandle   = 7
	VT_ID3D11Fence_SetEventOnCompletion = 8

	// ID3D11Query
	VT_ID3D11Query_GetDesc = 8

	// ID3D11Query1
	VT_ID3D11Query1_GetDesc1 = 9

	// ID3D11RasterizerState
	VT_ID3D11RasterizerState_GetDesc = 7

	// ID3D11RasterizerState1
	VT_ID3D11RasterizerState1_GetDesc1 = 8

	// ID3D11RasterizerState2
	VT_ID3D11RasterizerState2_GetDesc2 = 9

	// ID3D11RenderTargetView
	VT_ID3D11RenderTargetView_GetDesc = 8

	// ID3D11RenderTargetView1
	VT_ID3D11RenderTargetView1_GetDesc1 = 9

	// ID3D11Resource
	VT_ID3D11Resource_GetType             = 7
	VT_ID3D11Resource_SetEvictionPriority = 8
	VT_ID3D11Resource_GetEvictionPriority = 9

	// ID3D11SamplerState
	VT_ID3D11SamplerState_GetDesc = 7

	// ID3D11ShaderResourceView
	VT_ID3D11ShaderResourceView_GetDesc = 8

	// ID3D11ShaderResourceView1
	VT_ID3D11ShaderResourceView1_GetDesc1 = 9

	// ID3D11Texture1D
	VT_ID3D11Texture1D_GetDesc = 10

	// ID3D11Texture2D
	VT_ID3D11Texture2D_GetDesc = 10

	// ID3D11Texture2D1
	VT_ID3D11Texture2D1_GetDesc1 = 11

	// ID3D11Texture3D
	VT_ID3D11Texture3D_GetDesc = 10

	// ID3D11Texture3D1
	VT_ID3D11Texture3D1_GetDesc1 = 11

	// ID3D11UnorderedAccessView
	VT_ID3D11UnorderedAccessView_GetDesc = 8

	// ID3D11UnorderedAccessView1
	VT_ID3D11UnorderedAccessView1_GetDesc1 = 9

	// ID3D11VideoContext
	VT_ID3D11VideoContext_GetDecoderBuffer                          = 7
	VT_ID3D11VideoContext_ReleaseDecoderBuffer                      = 8
	VT_ID3D11VideoContext_DecoderBeginFrame                         = 9
	VT_ID3D11VideoContext_DecoderEndFrame                           = 10
	VT_ID3D11VideoContext_SubmitDecoderBuffers                      = 11
	VT_ID3D11VideoContext_VideoProcessorSetOutputTargetRect         = 12
	VT_ID3D11VideoContext_VideoProcessorSetOutputBackgroundColor    = 13
	VT_ID3D11VideoContext_VideoProcessorSetOutputColorSpace         = 14
	VT_ID3D11VideoContext_VideoProcessorSetOutputAlphaFillMode      = 15
	VT_ID3D11VideoContext_VideoProcessorSetOutputConstriction       = 16
	VT_ID3D11VideoContext_VideoProcessorSetOutputStereoMode         = 17
	VT_ID3D11VideoContext_VideoProcessorGetOutputTargetRect         = 18
	VT_ID3D11VideoContext_VideoProcessorGetOutputBackgroundColor    = 19
	VT_ID3D11VideoContext_VideoProcessorGetOutputColorSpace         = 20
	VT_ID3D11VideoContext_VideoProcessorGetOutputAlphaFillMode      = 21
	VT_ID3D11VideoContext_VideoProcessorGetOutputConstriction       = 22
	VT_ID3D11VideoContext_VideoProcessorGetOutputStereoMode         = 23
	VT_ID3D11VideoContext_VideoProcessorSetStreamFrameFormat        = 24
	VT_ID3D11VideoContext_VideoProcessorSetStreamColorSpace         = 25
	VT_ID3D11VideoContext_VideoProcessorSetStreamOutputRate         = 26
	VT_ID3D11VideoContext_VideoProcessorSetStreamSourceRect         = 27
	VT_ID3D11VideoContext_VideoProcessorSetStreamDestRect           = 28
	VT_ID3D11VideoContext_VideoProcessorSetStreamAlpha              = 29
	VT_ID3D11VideoContext_VideoProcessorSetStreamPalette            = 30
	VT_ID3D11VideoContext_VideoProcessorSetStreamPixelAspectRatio   = 31
	VT_ID3D11VideoContext_VideoProcessorSetStreamLumaKey            = 32
	VT_ID3D11VideoContext_VideoProcessorSetStreamStereoFormat       = 33
	VT_ID3D11VideoContext_VideoProcessorSetStreamAutoProcessingMode = 34
	VT_ID3D11VideoContext_VideoProcessorSetStreamFilter             = 35
	VT_ID3D11VideoContext_VideoProcessorGetStreamFrameFormat        = 36
	VT_ID3D11VideoContext_VideoProcessorGetStreamColorSpace         = 37
	VT_ID3D11VideoContext_VideoProcessorGetStreamOutputRate         = 38
	VT_ID3D11VideoContext_VideoProcessorGetStreamSourceRect         = 39
	VT_ID3D11VideoContext_VideoProcessorGetStreamDestRect           = 40
	VT_ID3D11VideoContext_VideoProcessorGetStreamAlpha              = 41
	VT_ID3D11VideoContext_VideoProcessorGetStreamPalette            = 42
	VT_ID3D11VideoContext_VideoProcessorGetStreamPixelAspectRatio   = 43
	VT_ID3D11VideoContext_VideoProcessorGetStreamLumaKey            = 44
	VT_ID3D11VideoContext_VideoProcessorGetStreamStereoFormat       = 45
	VT_ID3D11VideoContext_VideoProcessorGetStreamAutoProcessingMode = 46
	VT_ID3D11VideoContext_VideoProcessorGetStreamFilter             = 47
	VT_ID3D11VideoContext_VideoProcessorBlt                         = 48
	VT_ID3D11VideoContext_NegotiateCryptoSessionKeyExchange         = 49
	VT_ID3D11VideoContext_EncryptionBlt                             = 50
	VT_ID3D11VideoContext_DecryptionBlt                             = 51
	VT_ID3D11VideoContext_StartSessionKeyRefresh                    = 52
	VT_ID3D11VideoContext_FinishSessionKeyRefresh                   = 53
	VT_ID3D11VideoContext_GetEncryptionBltKey                       = 54
	VT_ID3D11VideoContext_NegotiateAuthenticatedChannelKeyExchange  = 55
	VT_ID3D11VideoContext_QueryAuthenticatedChannel                 = 56
	VT_ID3D11VideoContext_ConfigureAuthenticatedChannel             = 57
	VT_ID3D11VideoContext_VideoProcessorSetStreamRotation           = 58
	VT_ID3D11VideoContext_VideoProcessorGetStreamRotation           = 59

	// ID3D11VideoContext1
	VT_ID3D11VideoContext1_SubmitDecoderBuffers1              = 60
	VT_ID3D11VideoContext1_GetDataForNewHardwareKey           = 61
	VT_ID3D11VideoContext1_CheckCryptoSessionStatus           = 62
	VT_ID3D11VideoContext1_DecoderEnableDownsampling          = 63
	VT_ID3D11VideoContext1_DecoderUpdateDownsampling          = 64
	VT_ID3D11VideoContext1_VideoProcessorSetOutputColorSpace1 = 65
	VT_ID3D11VideoContext1_VideoProcessorSetOutputShaderUsage = 66
	VT_ID3D11VideoContext1_VideoProcessorGetOutputColorSpace1 = 67
	VT_ID3D11VideoContext1_VideoProcessorGetOutputShaderUsage = 68
	VT_ID3D11VideoContext1_VideoProcessorSetStreamColorSpace1 = 69
	VT_ID3D11VideoContext1_VideoProcessorSetStreamMirror      = 70
	VT_ID3D11VideoContext1_VideoProcessorGetStreamColorSpace1 = 71
	VT_ID3D11VideoContext1_VideoProcessorGetStreamMirror      = 72
	VT_ID3D11VideoContext1_VideoProcessorGetBehaviorHints     = 73

	// ID3D11VideoDecoder
	VT_ID3D11VideoDecoder_GetCreationParameters = 7
	VT_ID3D11VideoDecoder_GetDriverHandle       = 8

	// ID3D11VideoDecoderOutputView
	VT_ID3D11VideoDecoderOutputView_GetDesc = 8

	// ID3D11VideoDevice
	VT_ID3D11VideoDevice_CreateVideoDecoder             = 3
	VT_ID3D11VideoDevice_CreateVideoProcessor           = 4
	VT_ID3D11VideoDevice_CreateAuthenticatedChannel     = 5
	VT_ID3D11VideoDevice_CreateCryptoSession            = 6
	VT_ID3D11VideoDevice_CreateVideoDecoderOutputView   = 7
	VT_ID3D11VideoDevice_CreateVideoProcessorInputView  = 8
	VT_ID3D11VideoDevice_CreateVideoProcessorOutputView = 9
	VT_ID3D11VideoDevice_CreateVideoProcessorEnumerator = 10
	VT_ID3D11VideoDevice_GetVideoDecoderProfileCount    = 11
	VT_ID3D11VideoDevice_GetVideoDecoderProfile         = 12
	VT_ID3D11VideoDevice_CheckVideoDecoderFormat        = 13
	VT_ID3D11VideoDevice_GetVideoDecoderConfigCount     = 14
	VT_ID3D11VideoDevice_GetVideoDecoderConfig          = 15
	VT_ID3D11VideoDevice_GetContentProtectionCaps       = 16
	VT_ID3D11VideoDevice_CheckCryptoKeyExchange         = 17
	VT_ID3D11VideoDevice_SetPrivateData                 = 18
	VT_ID3D11VideoDevice_SetPrivateDataInterface        = 19

	// ID3D11VideoDevice1
	VT_ID3D11VideoDevice1_GetCryptoSessionPrivateDataSize           = 20
	VT_ID3D11VideoDevice1_GetVideoDecoderCaps                       = 21
	VT_ID3D11VideoDevice1_CheckVideoDecoderDownsampling             = 22
	VT_ID3D11VideoDevice1_RecommendVideoDecoderDownsampleParameters = 23

	// ID3D11VideoProcessor
	VT_ID3D11VideoProcessor_GetContentDesc        = 7
	VT_ID3D11VideoProcessor_GetRateConversionCaps = 8

	// ID3D11VideoProcessorEnumerator
	VT_ID3D11VideoProcessorEnumerator_GetVideoProcessorContentDesc        = 7
	VT_ID3D11VideoProcessorEnumerator_CheckVideoProcessorFormat           = 8
	VT_ID3D11VideoProcessorEnumerator_GetVideoProcessorCaps               = 9
	VT_ID3D11VideoProcessorEnumerator_GetVideoProcessorRateConversionCaps = 10
	VT_ID3D11VideoProcessorEnumerator_GetVideoProcessorCustomRate         = 11
	VT_ID3D11VideoProcessorEnumerator_GetVideoProcessorFilterRange        = 12

	// ID3D11VideoProcessorEnumerator1
	VT_ID3D11VideoProcessorEnumerator1_CheckVideoProcessorFormatConversion = 13

	// ID3D11VideoProcessorInputView
	VT_ID3D11VideoProcessorInputView_GetDesc = 8

	// ID3D11VideoProcessorOutputView
	VT_ID3D11VideoProcessorOutputView_GetDesc = 8

	// ID3D11View
	VT_ID3D11View_GetResource = 7

	// ID3DUserDefinedAnnotation
	VT_ID3DUserDefinedAnnotation_SetMarker = 3
	VT_ID3DUserDefinedAnnotation_GetStatus = 4

	// IDXGIAdapter
	VT_IDXGIAdapter_EnumOutputs           = 7
	VT_IDXGIAdapter_GetDesc               = 8
	VT_IDXGIAdapter_CheckInterfaceSupport = 9

	// IDXGIAdapter1
	VT_IDXGIAdapter1_GetDesc1 = 10

	// IDXGIAdapter2
	VT_IDXGIAdapter2_GetDesc2 = 11

	// IDXGIAdapter3
	VT_IDXGIAdapter3_RegisterHardwareContentProtectionTeardownStatusEvent = 12
	VT_IDXGIAdapter3_UnregisterHardwareContentProtectionTeardownStatus    = 13
	VT_IDXGIAdapter3_QueryVideoMemoryInfo                                 = 14
	VT_IDXGIAdapter3_SetVideoMemoryReservation                            = 15
	VT_IDXGIAdapter3_RegisterVideoMemoryBudgetChangeNotificationEvent     = 16
	VT_IDXGIAdapter3_UnregisterVideoMemoryBudgetChangeNotification        = 17

	// IDXGIAdapter4
	VT_IDXGIAdapter4_GetDesc3 = 18

	// IDXGIDecodeSwapChain
	VT_IDXGIDecodeSwapChain_PresentBuffer = 3
	VT_IDXGIDecodeSwapChain_SetSourceRect = 4
	VT_IDXGIDecodeSwapChain_SetTargetRect = 5
	VT_IDXGIDecodeSwapChain_SetDestSize   = 6
	VT_IDXGIDecodeSwapChain_GetSourceRect = 7
	VT_IDXGIDecodeSwapChain_GetTargetRect = 8
	VT_IDXGIDecodeSwapChain_GetDestSize   = 9
	VT_IDXGIDecodeSwapChain_SetColorSpace = 10
	VT_IDXGIDecodeSwapChain_GetColorSpace = 11

	// IDXGIDevice
	VT_IDXGIDevice_GetAdapter             = 7
	VT_IDXGIDevice_CreateSurface          = 8
	VT_IDXGIDevice_QueryResourceResidency = 9
	VT_IDXGIDevice_SetGPUThreadPriority   = 10
	VT_IDXGIDevice_GetGPUThreadPriority   = 11

	// IDXGIDevice1
	VT_IDXGIDevice1_SetMaximumFrameLatency = 12
	VT_IDXGIDevice1_GetMaximumFrameLatency = 13

	// IDXGIDevice2
	VT_IDXGIDevice2_OfferResources   = 14
	VT_IDXGIDevice2_ReclaimResources = 15
	VT_IDXGIDevice2_EnqueueSetEvent  = 16

	// IDXGIDevice3
	VT_IDXGIDevice3_Trim = 17

	// IDXGIDevice4
	VT_IDXGIDevice4_OfferResources1   = 18
	VT_IDXGIDevice4_ReclaimResources1 = 19

	// IDXGIDeviceSubObject
	VT_IDXGIDeviceSubObject_GetDevice = 7

	// IDXGIDisplayControl
	VT_IDXGIDisplayControl_IsStereoEnabled  = 3
	VT_IDXGIDisplayControl_SetStereoEnabled = 4

	// IDXGIFactory
	VT_IDXGIFactory_EnumAdapters          = 7
	VT_IDXGIFactory_MakeWindowAssociation = 8
	VT_IDXGIFactory_GetWindowAssociation  = 9
	VT_IDXGIFactory_CreateSwapChain       = 10
	VT_IDXGIFactory_CreateSoftwareAdapter = 11

	// IDXGIFactory1
	VT_IDXGIFactory1_EnumAdapters1 = 12
	VT_IDXGIFactory1_IsCurrent     = 13

	// IDXGIFactory2
	VT_IDXGIFactory2_IsWindowedStereoEnabled       = 14
	VT_IDXGIFactory2_CreateSwapChainForHwnd        = 15
	VT_IDXGIFactory2_CreateSwapChainForCoreWindow  = 16
	VT_IDXGIFactory2_GetSharedResourceAdapterLuid  = 17
	VT_IDXGIFactory2_RegisterStereoStatusWindow    = 18
	VT_IDXGIFactory2_RegisterStereoStatusEvent     = 19
	VT_IDXGIFactory2_UnregisterStereoStatus        = 20
	VT_IDXGIFactory2_RegisterOcclusionStatusWindow = 21
	VT_IDXGIFactory2_RegisterOcclusionStatusEvent  = 22
	VT_IDXGIFactory2_UnregisterOcclusionStatus     = 23
	VT_IDXGIFactory2_CreateSwapChainForComposition = 24

	// IDXGIFactory3
	VT_IDXGIFactory3_GetCreationFlags = 25

	// IDXGIFactory4
	VT_IDXGIFactory4_EnumAdapterByLuid = 26
	VT_IDXGIFactory4_EnumWarpAdapter   = 27

	// IDXGIFactory5
	VT_IDXGIFactory5_CheckFeatureSupport = 28

	// IDXGIFactory6
	VT_IDXGIFactory6_EnumAdapterByGpuPreference = 29

	// IDXGIFactory7
	VT_IDXGIFactory7_RegisterAdaptersChangedEvent   = 30
	VT_IDXGIFactory7_UnregisterAdaptersChangedEvent = 31

	// IDXGIFactoryMedia
	VT_IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle       = 3
	VT_IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle = 4

	// IDXGIKeyedMutex
	VT_IDXGIKeyedMutex_AcquireSync = 8
	VT_IDXGIKeyedMutex_ReleaseSync = 9

	// IDXGIObject
	VT_IDXGIObject_SetPrivateData          = 3
	VT_IDXGIObject_SetPrivateDataInterface = 4
	VT_IDXGIObject_GetPrivateData          = 5
	VT_IDXGIObject_GetParent               = 6

	// IDXGIOutput
	VT_IDXGIOutput_GetDesc                     = 7
	VT_IDXGIOutput_GetDisplayModeList          = 8
	VT_IDXGIOutput_FindClosestMatchingMode     = 9
	VT_IDXGIOutput_WaitForVBlank               = 10
	VT_IDXGIOutput_TakeOwnership               = 11
	VT_IDXGIOutput_ReleaseOwnership            = 12
	VT_IDXGIOutput_GetGammaControlCapabilities = 13
	VT_IDXGIOutput_SetGammaControl             = 14
	VT_IDXGIOutput_GetGammaControl             = 15
	VT_IDXGIOutput_SetDisplaySurface           = 16
	VT_IDXGIOutput_GetDisplaySurfaceData       = 17
	VT_IDXGIOutput_GetFrameStatistics          = 18

	// IDXGIOutput1
	VT_IDXGIOutput1_GetDisplayModeList1      = 19
	VT_IDXGIOutput1_FindClosestMatchingMode1 = 20
	VT_IDXGIOutput1_GetDisplaySurfaceData1   = 21
	VT_IDXGIOutput1_DuplicateOutput          = 22

	// IDXGIOutput2
	VT_IDXGIOutput2_SupportsOverlays = 23

	// IDXGIOutput3
	VT_IDXGIOutput3_CheckOverlaySupport = 24

	// IDXGIOutput4
	VT_IDXGIOutput4_CheckOverlayColorSpaceSupport = 25

	// IDXGIOutput5
	VT_IDXGIOutput5_DuplicateOutput1 = 26

	// IDXGIOutput6
	VT_IDXGIOutput6_GetDesc1                        = 27
	VT_IDXGIOutput6_CheckHardwareCompositionSupport = 28

	// IDXGIOutputDuplication
	VT_IDXGIOutputDuplication_GetDesc              = 7
	VT_IDXGIOutputDuplication_AcquireNextFrame     = 8
	VT_IDXGIOutputDuplication_GetFrameDirtyRects   = 9
	VT_IDXGIOutputDuplication_GetFrameMoveRects    = 10
	VT_IDXGIOutputDuplication_GetFramePointerShape = 11
	VT_IDXGIOutputDuplication_MapDesktopSurface    = 12
	VT_IDXGIOutputDuplication_UnMapDesktopSurface  = 13
	VT_IDXGIOutputDuplication_ReleaseFrame         = 14

	// IDXGIResource
	VT_IDXGIResource_GetSharedHandle     = 8
	VT_IDXGIResource_GetUsage            = 9
	VT_IDXGIResource_SetEvictionPriority = 10
	VT_IDXGIResource_GetEvictionPriority = 11

	// IDXGIResource1
	VT_IDXGIResource1_CreateSubresourceSurface = 12
	VT_IDXGIResource1_CreateSharedHandle       = 13

	// IDXGISurface
	VT_IDXGISurface_GetDesc = 8
	VT_IDXGISurface_Map     = 9
	VT_IDXGISurface_Unmap   = 10

	// IDXGISurface1
	VT_IDXGISurface1_GetDC     = 11
	VT_IDXGISurface1_ReleaseDC = 12

	// IDXGISurface2
	VT_IDXGISurface2_GetResource = 13

	// IDXGISwapChain
	VT_IDXGISwapChain_Present             = 8
	VT_IDXGISwapChain_GetBuffer           = 9
	VT_IDXGISwapChain_SetFullscreenState  = 10
	VT_IDXGISwapChain_GetFullscreenState  = 11
	VT_IDXGISwapChain_GetDesc             = 12
	VT_IDXGISwapChain_ResizeBuffers       = 13
	VT_IDXGISwapChain_ResizeTarget        = 14
	VT_IDXGISwapChain_GetContainingOutput = 15
	VT_IDXGISwapChain_GetFrameStatistics  = 16
	VT_IDXGISwapChain_GetLastPresentCount = 17

	// IDXGISwapChain1
	VT_IDXGISwapChain1_GetDesc1                 = 18
	VT_IDXGISwapChain1_GetFullscreenDesc        = 19
	VT_IDXGISwapChain1_GetHwnd                  = 20
	VT_IDXGISwapChain1_GetCoreWindow            = 21
	VT_IDXGISwapChain1_Present1                 = 22
	VT_IDXGISwapChain1_IsTemporaryMonoSupported = 23
	VT_IDXGISwapChain1_GetRestrictToOutput      = 24
	VT_IDXGISwapChain1_SetBackgroundColor       = 25
	VT_IDXGISwapChain1_GetBackgroundColor       = 26
	VT_IDXGISwapChain1_SetRotation              = 27
	VT_IDXGISwapChain1_GetRotation              = 28

	// IDXGISwapChain2
	VT_IDXGISwapChain2_SetSourceSize                 = 29
	VT_IDXGISwapChain2_GetSourceSize                 = 30
	VT_IDXGISwapChain2_SetMaximumFrameLatency        = 31
	VT_IDXGISwapChain2_GetMaximumFrameLatency        = 32
	VT_IDXGISwapChain2_GetFrameLatencyWaitableObject = 33
	VT_IDXGISwapChain2_SetMatrixTransform            = 34
	VT_IDXGISwapChain2_GetMatrixTransform            = 35

	// IDXGISwapChain3
	VT_IDXGISwapChain3_GetCurrentBackBufferIndex = 36
	VT_IDXGISwapChain3_CheckColorSpaceSupport    = 37
	VT_IDXGISwapChain3_SetColorSpace1            = 38
	VT_IDXGISwapChain3_ResizeBuffers1            = 39

	// IDXGISwapChain4
	VT_IDXGISwapChain4_SetHDRMetaData = 40

	// IDXGISwapChainMedia
	VT_IDXGISwapChainMedia_GetFrameStatisticsMedia     = 3
	VT_IDXGISwapChainMedia_SetPresentDuration          = 4
	VT_IDXGISwapChainMedia_CheckPresentDurationSupport = 5
)

// === 摘要 ===
// ID3D11Asynchronous: 1 methods (vtable slots 7-7)
// ID3D11AuthenticatedChannel: 3 methods (vtable slots 7-9)
// ID3D11BlendState: 1 methods (vtable slots 7-7)
// ID3D11BlendState1: 1 methods (vtable slots 8-8)
// ID3D11Buffer: 1 methods (vtable slots 10-10)
// ID3D11ClassInstance: 4 methods (vtable slots 7-10)
// ID3D11ClassLinkage: 2 methods (vtable slots 7-8)
// ID3D11CommandList: 1 methods (vtable slots 7-7)
// ID3D11Counter: 1 methods (vtable slots 8-8)
// ID3D11CryptoSession: 5 methods (vtable slots 7-11)
// ID3D11DepthStencilState: 1 methods (vtable slots 7-7)
// ID3D11DepthStencilView: 1 methods (vtable slots 8-8)
// ID3D11Device: 40 methods (vtable slots 3-42)
// ID3D11Device1: 7 methods (vtable slots 43-49)
// ID3D11Device2: 4 methods (vtable slots 50-53)
// ID3D11Device3: 11 methods (vtable slots 54-64)
// ID3D11DeviceChild: 4 methods (vtable slots 3-6)
// ID3D11DeviceContext: 108 methods (vtable slots 7-114)
// ID3D11DeviceContext1: 19 methods (vtable slots 115-133)
// ID3D11DeviceContext2: 10 methods (vtable slots 134-143)
// ID3D11DeviceContext3: 3 methods (vtable slots 144-146)
// ID3D11DeviceContext4: 2 methods (vtable slots 147-148)
// ID3D11Fence: 2 methods (vtable slots 7-8)
// ID3D11Query: 1 methods (vtable slots 8-8)
// ID3D11Query1: 1 methods (vtable slots 9-9)
// ID3D11RasterizerState: 1 methods (vtable slots 7-7)
// ID3D11RasterizerState1: 1 methods (vtable slots 8-8)
// ID3D11RasterizerState2: 1 methods (vtable slots 9-9)
// ID3D11RenderTargetView: 1 methods (vtable slots 8-8)
// ID3D11RenderTargetView1: 1 methods (vtable slots 9-9)
// ID3D11Resource: 3 methods (vtable slots 7-9)
// ID3D11SamplerState: 1 methods (vtable slots 7-7)
// ID3D11ShaderResourceView: 1 methods (vtable slots 8-8)
// ID3D11ShaderResourceView1: 1 methods (vtable slots 9-9)
// ID3D11Texture1D: 1 methods (vtable slots 10-10)
// ID3D11Texture2D: 1 methods (vtable slots 10-10)
// ID3D11Texture2D1: 1 methods (vtable slots 11-11)
// ID3D11Texture3D: 1 methods (vtable slots 10-10)
// ID3D11Texture3D1: 1 methods (vtable slots 11-11)
// ID3D11UnorderedAccessView: 1 methods (vtable slots 8-8)
// ID3D11UnorderedAccessView1: 1 methods (vtable slots 9-9)
// ID3D11VideoContext: 53 methods (vtable slots 7-59)
// ID3D11VideoContext1: 14 methods (vtable slots 60-73)
// ID3D11VideoDecoder: 2 methods (vtable slots 7-8)
// ID3D11VideoDecoderOutputView: 1 methods (vtable slots 8-8)
// ID3D11VideoDevice: 17 methods (vtable slots 3-19)
// ID3D11VideoDevice1: 4 methods (vtable slots 20-23)
// ID3D11VideoProcessor: 2 methods (vtable slots 7-8)
// ID3D11VideoProcessorEnumerator: 6 methods (vtable slots 7-12)
// ID3D11VideoProcessorEnumerator1: 1 methods (vtable slots 13-13)
// ID3D11VideoProcessorInputView: 1 methods (vtable slots 8-8)
// ID3D11VideoProcessorOutputView: 1 methods (vtable slots 8-8)
// ID3D11View: 1 methods (vtable slots 7-7)
// ID3DUserDefinedAnnotation: 2 methods (vtable slots 3-4)
// IDXGIAdapter: 3 methods (vtable slots 7-9)
// IDXGIAdapter1: 1 methods (vtable slots 10-10)
// IDXGIAdapter2: 1 methods (vtable slots 11-11)
// IDXGIAdapter3: 6 methods (vtable slots 12-17)
// IDXGIAdapter4: 1 methods (vtable slots 18-18)
// IDXGIDecodeSwapChain: 9 methods (vtable slots 3-11)
// IDXGIDevice: 5 methods (vtable slots 7-11)
// IDXGIDevice1: 2 methods (vtable slots 12-13)
// IDXGIDevice2: 3 methods (vtable slots 14-16)
// IDXGIDevice3: 1 methods (vtable slots 17-17)
// IDXGIDevice4: 2 methods (vtable slots 18-19)
// IDXGIDeviceSubObject: 1 methods (vtable slots 7-7)
// IDXGIDisplayControl: 2 methods (vtable slots 3-4)
// IDXGIFactory: 5 methods (vtable slots 7-11)
// IDXGIFactory1: 2 methods (vtable slots 12-13)
// IDXGIFactory2: 11 methods (vtable slots 14-24)
// IDXGIFactory3: 1 methods (vtable slots 25-25)
// IDXGIFactory4: 2 methods (vtable slots 26-27)
// IDXGIFactory5: 1 methods (vtable slots 28-28)
// IDXGIFactory6: 1 methods (vtable slots 29-29)
// IDXGIFactory7: 2 methods (vtable slots 30-31)
// IDXGIFactoryMedia: 2 methods (vtable slots 3-4)
// IDXGIKeyedMutex: 2 methods (vtable slots 8-9)
// IDXGIObject: 4 methods (vtable slots 3-6)
// IDXGIOutput: 12 methods (vtable slots 7-18)
// IDXGIOutput1: 4 methods (vtable slots 19-22)
// IDXGIOutput2: 1 methods (vtable slots 23-23)
// IDXGIOutput3: 1 methods (vtable slots 24-24)
// IDXGIOutput4: 1 methods (vtable slots 25-25)
// IDXGIOutput5: 1 methods (vtable slots 26-26)
// IDXGIOutput6: 2 methods (vtable slots 27-28)
// IDXGIOutputDuplication: 8 methods (vtable slots 7-14)
// IDXGIResource: 4 methods (vtable slots 8-11)
// IDXGIResource1: 2 methods (vtable slots 12-13)
// IDXGISurface: 3 methods (vtable slots 8-10)
// IDXGISurface1: 2 methods (vtable slots 11-12)
// IDXGISurface2: 1 methods (vtable slots 13-13)
// IDXGISwapChain: 10 methods (vtable slots 8-17)
// IDXGISwapChain1: 11 methods (vtable slots 18-28)
// IDXGISwapChain2: 7 methods (vtable slots 29-35)
// IDXGISwapChain3: 4 methods (vtable slots 36-39)
// IDXGISwapChain4: 1 methods (vtable slots 40-40)
// IDXGISwapChainMedia: 3 methods (vtable slots 3-5)
