package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type Interface struct {
	Name    string
	Base    string
	Methods []string
}

var (
	reIfLine        = regexp.MustCompile(`interface\s+(\w+)\s*:\s*(\w+)`)
	reMethod        = regexp.MustCompile(`\b(\w+)\s*\([^)]*\)\s*;`)
	reVoidMethod    = regexp.MustCompile(`\bvoid\s+(\w+)\s*\(`)
	reHRESULTMethod = regexp.MustCompile(`\bHRESULT\s+(\w+)\s*\(`)
	reOtherMethod   = regexp.MustCompile(`\b(?:UINT|BOOL|LONG|ULONG|FLOAT|DOUBLE|HANDLE|LUID|LARGE_INTEGER|DXGI_\w+|D3D\w+|REFGUID|REFIID|IUnknown|ID3D\w+)\s+(\w+)\s*\(`)
)

func parseIDLFile(path string) []Interface {
	f, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer f.Close()

	var result []Interface
	var cur *Interface
	scanner := bufio.NewScanner(f)

	var lines []string
	for scanner.Scan() {
		lines = append(lines, scanner.Text())
	}

	var merged []string
	var buf strings.Builder
	braceDepth := 0

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "//") {
			if buf.Len() > 0 {
				buf.WriteString(" ")
			}
			continue
		}

		for _, ch := range trimmed {
			if ch == '{' {
				braceDepth++
			}
			if ch == '}' {
				braceDepth--
				if braceDepth <= 0 {
					braceDepth = 0
				}
			}
		}

		if buf.Len() > 0 {
			buf.WriteString(" ")
			buf.WriteString(trimmed)
		} else {
			buf.WriteString(trimmed)
		}

		if strings.Contains(trimmed, ";") || trimmed == "};" || trimmed == "{" {
			merged = append(merged, buf.String())
			buf.Reset()
		}
	}
	if buf.Len() > 0 {
		merged = append(merged, buf.String())
	}

	for _, line := range merged {
		if cur == nil {
			if m := reIfLine.FindStringSubmatch(line); m != nil {
				cur = &Interface{Name: m[1], Base: m[2]}
			}
			continue
		}

		if strings.Contains(line, "};") {
			result = append(result, *cur)
			cur = nil
			continue
		}

		if strings.HasPrefix(line, "[") || strings.HasPrefix(line, "cpp_quote") || strings.HasPrefix(line, "typedef") || strings.HasPrefix(line, "enum") || strings.HasPrefix(line, "struct") || strings.HasPrefix(line, "library") || strings.HasPrefix(line, "coclass") || strings.HasPrefix(line, "import") {
			continue
		}

		if m := reVoidMethod.FindStringSubmatch(line); m != nil {
			cur.Methods = append(cur.Methods, m[1])
		} else if m := reHRESULTMethod.FindStringSubmatch(line); m != nil {
			cur.Methods = append(cur.Methods, m[1])
		} else if m := reOtherMethod.FindStringSubmatch(line); m != nil {
			cur.Methods = append(cur.Methods, m[1])
		}
	}

	return result
}

func main() {
	idlDir := "idl"
	if len(os.Args) > 1 {
		idlDir = os.Args[1]
	}

	entries, err := os.ReadDir(idlDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "无法读取目录 %s: %v\n", idlDir, err)
		os.Exit(1)
	}

	var allIfaces []Interface
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".idl") {
			ifaces := parseIDLFile(filepath.Join(idlDir, e.Name()))
			allIfaces = append(allIfaces, ifaces...)
		}
	}

	byName := make(map[string]*Interface)
	for i := range allIfaces {
		byName[allIfaces[i].Name] = &allIfaces[i]
	}

	type Entry struct {
		Iface, Method string
		Index         int
	}
	var vt []Entry

	for i := range allIfaces {
		iface := &allIfaces[i]
		baseIdx := 0
		for baseName := iface.Base; baseName != "" && baseName != "IUnknown"; {
			base, ok := byName[baseName]
			if !ok {
				break
			}
			baseIdx += len(base.Methods)
			baseName = base.Base
		}
		baseIdx += 3

		for j, m := range iface.Methods {
			vt = append(vt, Entry{iface.Name, m, baseIdx + j})
		}
	}

	sort.Slice(vt, func(i, j int) bool {
		if vt[i].Iface != vt[j].Iface {
			return vt[i].Iface < vt[j].Iface
		}
		return vt[i].Index < vt[j].Index
	})

	fmt.Println("// Code generated by idlgen. DO NOT EDIT.")
	fmt.Println("// Source: Windows SDK IDL files (d3d11.idl, dxgi.idl, etc.)")
	fmt.Println("package main")
	fmt.Println()
	fmt.Println("// COM vtable 方法索引常量（含继承链）")
	fmt.Println("const (")

	last := ""
	for _, e := range vt {
		if e.Iface != last {
			if last != "" {
				fmt.Println()
			}
			fmt.Printf("\t// %s\n", e.Iface)
			last = e.Iface
		}
		fmt.Printf("\t%-55s = %d\n", fmt.Sprintf("VT_%s_%s", e.Iface, e.Method), e.Index)
	}
	fmt.Println(")")
	fmt.Println()

	fmt.Println("// === 摘要 ===")
	summary := make(map[string][]Entry)
	for _, e := range vt {
		summary[e.Iface] = append(summary[e.Iface], e)
	}
	names := make([]string, 0, len(summary))
	for k := range summary {
		names = append(names, k)
	}
	sort.Strings(names)
	for _, n := range names {
		ms := summary[n]
		fmt.Printf("// %s: %d methods (vtable slots %d-%d)\n", n, len(ms), ms[0].Index, ms[len(ms)-1].Index)
	}
}
